/*
 * Vista para buscar series en la BBDD TMDBapi
 * Se introduce titulo y al pulsar en Buscar aparecen las series estrenadas que contengan ese título
 * 
 */
package ddr.pelisseries.vista;

import ddr.pelisseries.modelo.seriesEncontradas;
import info.movito.themoviedbapi.TmdbApi;
import info.movito.themoviedbapi.TmdbSearch;
import info.movito.themoviedbapi.TvResultsPage;
import info.movito.themoviedbapi.model.tv.TvSeries;
import java.awt.Image;
import java.io.IOException;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUIBuscarSerie extends javax.swing.JFrame {

    /**
     * Crear ventana Series Vistas
     */
    DefaultListModel<seriesEncontradas> encontradas = new DefaultListModel<>(); //definimos modelo lista clase seriesEncontradas
    String serieSeleccionada = ""; //variable que pasaremos como serieSeleccionada
    String estreno = "";
//    int idPeliSeleccionada = 0; //variable ID de pelil en la BBDD TMDB

    public GUIBuscarSerie() {
        initComponents();
        this.setLocationRelativeTo(null);
        jListBuscarSeriesEcontradas.setModel(encontradas);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonCerrarSeriesVistas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextBuscarSerie = new javax.swing.JTextField();
        jButtonBuscarSerie = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListBuscarSeriesEcontradas = new javax.swing.JList<>();
        poster = new javax.swing.JLabel();
        NuevaSerie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("Buscar Serie");

        jButtonCerrarSeriesVistas.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonCerrarSeriesVistas.setText("Cerrar");
        jButtonCerrarSeriesVistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarSeriesVistasActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setText("Título de la Serie:");

        jButtonBuscarSerie.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonBuscarSerie.setText("Buscar Serie");
        jButtonBuscarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarSerieActionPerformed(evt);
            }
        });

        jListBuscarSeriesEcontradas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListBuscarSeriesEcontradasMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jListBuscarSeriesEcontradas);

        poster.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        NuevaSerie.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        NuevaSerie.setIcon(new javax.swing.ImageIcon("D:\\Proyectos\\PelisSeries\\Imágenes\\Serie-icon45x45.png")); // NOI18N
        NuevaSerie.setText("Nueva Serie Vista");
        NuevaSerie.setMaximumSize(new java.awt.Dimension(209, 83));
        NuevaSerie.setMinimumSize(new java.awt.Dimension(209, 83));
        NuevaSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NuevaSerieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextBuscarSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(240, 240, 240)
                            .addComponent(jLabel1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NuevaSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBuscarSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(poster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCerrarSeriesVistas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextBuscarSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscarSerie))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(poster, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(NuevaSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCerrarSeriesVistas))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCerrarSeriesVistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarSeriesVistasActionPerformed
        // TODO add your handling code here:        
        this.setVisible(false);
        dispose();

    }//GEN-LAST:event_jButtonCerrarSeriesVistasActionPerformed

    private void jButtonBuscarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarSerieActionPerformed
        // Al pulsar el boton BUSCAR SERIE, lee el contenido del texto introducido y lo carga en la tabla
        String serieBuscada = jTextBuscarSerie.getText(); //almacenamos en variable el título de la serie

        if (serieBuscada.isEmpty()) {
            JOptionPane.showMessageDialog(null, "No se ha introducido ningún dato", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
        } else {
            TmdbSearch busqueda = new TmdbApi("f57ae39e733b57b4ffc7da40546e6f24").getSearch(); //cargamos api KEY personal
            TvResultsPage serie = busqueda.searchTv(serieBuscada, "es", null); //buscamos serie

            if (serie.getTotalResults() > 0) { //si hay serie

                for (TvSeries e : serie) {
                    seriesEncontradas serieencontrada = new seriesEncontradas(e.getName(), e.getFirstAirDate(), e.getId());

                    serieencontrada.setTitulo(e.getName());
                    serieencontrada.setIdSerie(e.getId());
                    serieencontrada.setEstreno(e.getFirstAirDate());
                    if (e.getPosterPath() == null) {
                        System.out.println("no hay");  ///si no hay poster.. habrá que poner otra imagen
                    } else {
                        serieencontrada.setUrlPoster(e.getPosterPath());

                    }

                    encontradas.addElement(serieencontrada);
                }
            } else {
                JOptionPane.showMessageDialog(null, "No se ha encontrado serie para la búsqueda realizada", "INFORMACION", JOptionPane.INFORMATION_MESSAGE);
            }
        }

    }//GEN-LAST:event_jButtonBuscarSerieActionPerformed

    private void jListBuscarSeriesEcontradasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListBuscarSeriesEcontradasMouseClicked
        // al seleccionar una peli en el JLIST
        serieSeleccionada = jListBuscarSeriesEcontradas.getSelectedValue().getTitulo();
        estreno = jListBuscarSeriesEcontradas.getSelectedValue().getEstreno();

        String txt = jListBuscarSeriesEcontradas.getSelectedValue().getUrlPoster();

        URL url;
        try {
            url = new URL(txt);
            Image image = ImageIO.read(url);
            Image img = image.getScaledInstance(139, 229, Image.SCALE_SMOOTH);
            poster.setIcon(new ImageIcon(img));
        } catch (MalformedURLException ex) {
            Logger.getLogger(GUIBuscarSerie.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(GUIBuscarSerie.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jListBuscarSeriesEcontradasMouseClicked

    private void NuevaSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NuevaSerieActionPerformed
        // Abrimos la ventana Nueva Serie Vista
        GUINuevaSerie nu = new GUINuevaSerie(serieSeleccionada, estreno);
        nu.setVisible(true);
    }//GEN-LAST:event_NuevaSerieActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIBuscarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIBuscarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIBuscarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIBuscarSerie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GUIBuscarSerie().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton NuevaSerie;
    private javax.swing.JButton jButtonBuscarSerie;
    private javax.swing.JButton jButtonCerrarSeriesVistas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JList<seriesEncontradas> jListBuscarSeriesEcontradas;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextBuscarSerie;
    private javax.swing.JLabel poster;
    // End of variables declaration//GEN-END:variables
}
