package ddr.pelisseries.vista;

import ddr.pelisseries.controlador.Controlador;
import ddr.pelisseries.modelo.peliculas;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUINuevaPeliFichero extends javax.swing.JFrame {

    /**
     * Creates new form GUINuevoUsuario
     * @param peliSeleccionada
     */
    
    
    public GUINuevaPeliFichero(String peliSeleccionada, String estreno) {
        initComponents();
        this.setLocationRelativeTo(null);
        tituloPeli.setText(peliSeleccionada);    
        fechaVista.setText(estreno);
    }
    
    public GUINuevaPeliFichero(String peliSeleccionada, String estreno, String fechaPeli) {
        initComponents();
        this.setLocationRelativeTo(null);
        tituloPeli.setText(peliSeleccionada);    
        estrenoPeli1.setText(estreno);
        fechaVista.setText(fechaPeli);
    }

    private GUINuevaPeliFichero() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tituloPeli = new javax.swing.JTextField();
        cancelBTPeliNueva = new javax.swing.JButton();
        acceptBTPeliNueva = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelEstreno = new javax.swing.JLabel();
        fechaVista = new javax.swing.JTextField();
        estrenoPeli1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setText("Nueva Peli Vista");

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel2.setText("Título de la peli:");

        jLabel3.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabel3.setText("Fecha Vista:");

        tituloPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloPeliActionPerformed(evt);
            }
        });

        cancelBTPeliNueva.setText("Cancelar");
        cancelBTPeliNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBTPeliNuevaActionPerformed(evt);
            }
        });

        acceptBTPeliNueva.setText("Aceptar");
        acceptBTPeliNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptBTPeliNuevaActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\Proyectos\\PelisSeries\\Imágenes\\palomitas-de-maiz_icono.png")); // NOI18N

        jLabelEstreno.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jLabelEstreno.setText("Fecha Estreno:");

        fechaVista.setEnabled(false);
        fechaVista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechaVistaActionPerformed(evt);
            }
        });

        estrenoPeli1.setEnabled(false);
        estrenoPeli1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estrenoPeli1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(cancelBTPeliNueva)
                                .addGap(78, 78, 78)
                                .addComponent(acceptBTPeliNueva))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelEstreno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tituloPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(fechaVista, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estrenoPeli1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(77, 77, 77)
                                .addComponent(jLabel4)))))
                .addGap(95, 95, 95)
                .addComponent(jLabel5)
                .addGap(46, 46, 46))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(tituloPeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(fechaVista, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabelEstreno)
                                    .addComponent(estrenoPeli1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(acceptBTPeliNueva)
                            .addComponent(cancelBTPeliNueva))))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tituloPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloPeliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tituloPeliActionPerformed

    private void cancelBTPeliNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBTPeliNuevaActionPerformed
        // TODO add your handling code here:
         setVisible(false);
         dispose();
   
    }//GEN-LAST:event_cancelBTPeliNuevaActionPerformed

    private void acceptBTPeliNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptBTPeliNuevaActionPerformed
        // TODO add your handling code here:
        
        if(tituloPeli.getText().isBlank())
        {
            JOptionPane.showMessageDialog(null, "Existen Campos Obligatorios Vacíos");
        }
        else
        {
              
            String nombrePeli = tituloPeli.getText();
            String fechaEstreno = estrenoPeli1.getText();
            String fechaPeli = fechaVista.getText();
           
            boolean response=false;

            peliculas nuevaPeli = new peliculas(nombrePeli,fechaPeli,fechaEstreno);
            response = Controlador.insertNuevaPeliBD(nuevaPeli);

            if(response)    {
                JOptionPane.showMessageDialog(null, "Operación realizada correctamente");
            }

            setVisible(false);
            dispose();
                
        }
        
    }//GEN-LAST:event_acceptBTPeliNuevaActionPerformed

    private void fechaVistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechaVistaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechaVistaActionPerformed

    private void estrenoPeli1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estrenoPeli1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estrenoPeli1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUINuevaPeliFichero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUINuevaPeliFichero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUINuevaPeliFichero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUINuevaPeliFichero.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUINuevaPeliFichero().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acceptBTPeliNueva;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton cancelBTPeliNueva;
    private javax.swing.JTextField estrenoPeli1;
    private javax.swing.JTextField fechaVista;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelEstreno;
    private javax.swing.JTextField tituloPeli;
    // End of variables declaration//GEN-END:variables
}
