package ddr.pelisseries.vista;

import ddr.pelisseries.controlador.Controlador;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import javax.swing.JOptionPane;

/**
 *
 * @author Usuario
 */
public class GUIPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form vistaPrincipal
     */
    public GUIPrincipal() {
        initComponents();

        this.setLocationRelativeTo(null);

        this.setVisible(true);

        if (!Controlador.validarConexiónBBDD()) {
            JOptionPane.showMessageDialog(null, "No hay Conexión con la BBDD SQL. Por favor Revise la configuración en la Clase ConexionBD.java");
            System.exit(0);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        PelisVistas = new javax.swing.JButton();
        jButtonActualizarSerie = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        PelisVistas1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        BuscarPeli = new javax.swing.JButton();
        BuscarSerie = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setUndecorated(true);
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Software de Control de Pelis y Series Vistas - PSVistas");

        PelisVistas.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        PelisVistas.setIcon(new javax.swing.ImageIcon("D:\\Proyectos\\PelisSeries\\Imágenes\\File-Movies-icon.png")); // NOI18N
        PelisVistas.setText("Pelis Vistas");
        PelisVistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PelisVistasActionPerformed(evt);
            }
        });

        jButtonActualizarSerie.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonActualizarSerie.setIcon(new javax.swing.ImageIcon("D:\\Proyectos\\PelisSeries\\Imágenes\\noche-de-pelicula_peque.png")); // NOI18N
        jButtonActualizarSerie.setText("Actualizar Serie Vista");
        jButtonActualizarSerie.setMaximumSize(new java.awt.Dimension(209, 83));
        jButtonActualizarSerie.setMinimumSize(new java.awt.Dimension(209, 83));
        jButtonActualizarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarSerieActionPerformed(evt);
            }
        });

        jButtonSalir.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        PelisVistas1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        PelisVistas1.setIcon(new javax.swing.ImageIcon("D:\\Proyectos\\PelisSeries\\Imágenes\\tv_series_icon_peque.png")); // NOI18N
        PelisVistas1.setText("Series Vistas");
        PelisVistas1.setMaximumSize(new java.awt.Dimension(209, 83));
        PelisVistas1.setMinimumSize(new java.awt.Dimension(209, 83));
        PelisVistas1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PelisVistas1ActionPerformed(evt);
            }
        });

        jLabel2.setText("\"Este producto utiliza la API de TMDB, pero TMDB no lo respalda ni lo certifica\".");

        BuscarPeli.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        BuscarPeli.setIcon(new javax.swing.ImageIcon("D:\\Proyectos\\PelisSeries\\Imágenes\\cine72x72.png")); // NOI18N
        BuscarPeli.setText("Buscar Peli");
        BuscarPeli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarPeliActionPerformed(evt);
            }
        });

        BuscarSerie.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        BuscarSerie.setIcon(new javax.swing.ImageIcon("D:\\Proyectos\\PelisSeries\\Imágenes\\series72x72.png")); // NOI18N
        BuscarSerie.setText("Buscar Serie");
        BuscarSerie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscarSerieActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Segoe Print", 1, 12)); // NOI18N
        jButton1.setText("Importación de Datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PelisVistas, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BuscarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PelisVistas1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BuscarSerie, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonActualizarSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(163, 163, 163))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(PelisVistas, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BuscarPeli, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PelisVistas1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonActualizarSerie, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BuscarSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(jButtonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PelisVistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PelisVistasActionPerformed
        // TODO add your handling code here:

        GUIPelisVistas ha = new GUIPelisVistas();
        ha.setVisible(true);
    }//GEN-LAST:event_PelisVistasActionPerformed

    private void jButtonActualizarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarSerieActionPerformed
        //Buscar serie y después actualizar
        GUIActualizarSerie bs = new GUIActualizarSerie();
        bs.setVisible(true);
    }//GEN-LAST:event_jButtonActualizarSerieActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:

        this.dispose();

    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void PelisVistas1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PelisVistas1ActionPerformed
        // Abrimos la ventana Series Vistas
        GUISeriesVistas sv = new GUISeriesVistas();
        sv.setVisible(true);
    }//GEN-LAST:event_PelisVistas1ActionPerformed

    private void BuscarPeliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarPeliActionPerformed
        // Abrimos buscador de pelis
        GUIBuscarPeli bp = new GUIBuscarPeli();
        bp.setVisible(true);
    }//GEN-LAST:event_BuscarPeliActionPerformed

    private void BuscarSerieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscarSerieActionPerformed
        // Abrimos buscador de series
        GUIBuscarSerie bs = new GUIBuscarSerie();
        bs.setVisible(true);
    }//GEN-LAST:event_BuscarSerieActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Al pulsar la Actualizar datos se debe pedir Serie o Peli
        String[] opcion = {"Serie", "Película"};
        int seleccion = JOptionPane.showOptionDialog(null, "Cargar fichero de Series o de Películas?", "Cargar datos de fichero CSV", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, opcion, opcion[0]);
        if (seleccion == 0) {       //si pulsa SERIE       
            BufferedReader reader = null;
            try { //comprobamos que exite fichero
                reader = new BufferedReader(new FileReader("D:\\Proyectos\\PelisSeries\\Datos Forms\\Serievista.csv")); 
                GUISeriesFichero sf = new GUISeriesFichero();
                sf.setVisible(true);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "No hay nuevo fichero CSV disponible", "FICHERO CSV no encontrado", JOptionPane.INFORMATION_MESSAGE);
            }
        } else if (seleccion == 1) { //si pulsa PELI
            BufferedReader reader = null;
            try { //comprobamos que exite fichero
                reader = new BufferedReader(new FileReader("D:\\Proyectos\\PelisSeries\\Datos Forms\\Pelivista.csv")); 
                GUIPelisFichero pf = new GUIPelisFichero();
                pf.setVisible(true);
            } catch (FileNotFoundException ex) {
                JOptionPane.showMessageDialog(null, "No hay nuevo fichero CSV disponible", "FICHERO CSV no encontrado", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscarPeli;
    private javax.swing.JButton BuscarSerie;
    private javax.swing.JButton PelisVistas;
    private javax.swing.JButton PelisVistas1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonActualizarSerie;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
